Update dast-scan.yml

diff --git a/.github/workflows/dast-scan.yml b/.github/workflows/dast-scan.yml
--- a/.github/workflows/dast-scan.yml
+++ b/.github/workflows/dast-scan.yml
@@ -33,7 +33,20 @@ jobs:
 
   # Step 5: Wait for the application to be ready
       - name: Wait for the application to start
-        run: sleep 30 
+        run: |
+          echo "Waiting for applciation to start on port 3000.."
+          timeout=60
+          while ! curl -s "http://localhost:3000"; do
+            sleep 5
+            timeout= $((timeout-5))
+            if [ $timeout -le 0]; then
+              echo "Error: Application did not start within the timeout period"
+              exit 1
+            fi 
+            exho "still waiting..."
+          done
+          echo "Application is up and running"
+      #  run: sleep 30 
 
   # Step 6 : Run the OWASP ZAP BAseline Scan 
       - name: ZAP Baseline scan 
@@ -44,8 +57,19 @@ jobs:
           cmd_options: '-J report.json'
  
   #Step 7: upload the zap report as a workflow artificat 
-      - name: Upload ZAP Report 
+ #     - name: Upload ZAP Report 
+  #      if: always() # will ensure this step runs even if the zap scan fails to the build 
+   #     uses: actions/upload-artifact@v4
+    #    with:
+     #     name: zap-scan-report
+      #    path: report.json
+
+      - name: List file in workspace 
         if: always() # will ensure this step runs even if the zap scan fails to the build 
+        run: ls - IR 
+
+      - name: Upload ZAP Report
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: zap-scan-report
